# Generated by Django 5.0.4 on 2024-04-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_salib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='images',
            field=models.ImageField(default='', upload_to='media/themes'),
        ),
    ]
